import dotenv from 'dotenv'
import { resolve } from 'path'

// Load environment variables
dotenv.config({ path: resolve(process.cwd(), '.env.local') })

/**
 * Test script to simulate Clerk webhook events.
 * 
 * This is useful for local development to test the webhook handler
 * without needing to configure Clerk webhooks or use ngrok.
 * 
 * Note: This bypasses signature verification for testing purposes.
 */

const WEBHOOK_URL = 'http://localhost:3000/api/webhooks/clerk'

// Sample webhook payloads
const sampleUserCreated = {
  type: 'user.created',
  data: {
    id: 'user_test123',
    email_addresses: [{ email_address: 'test@example.com' }],
    first_name: 'Test',
    last_name: 'User',
    image_url: 'https://example.com/avatar.jpg',
  },
}

const sampleUserUpdated = {
  type: 'user.updated',
  data: {
    id: 'user_test123',
    email_addresses: [{ email_address: 'updated@example.com' }],
    first_name: 'Updated',
    last_name: 'User',
    image_url: 'https://example.com/new-avatar.jpg',
  },
}

const sampleUserDeleted = {
  type: 'user.deleted',
  data: {
    id: 'user_test123',
  },
}

async function testWebhook(event: any) {
  console.log(`\n=== Testing ${event.type} ===\n`)
  
  try {
    const response = await fetch(WEBHOOK_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        // Note: In production, these headers would be generated by Clerk
        'svix-id': 'test_' + Date.now(),
        'svix-timestamp': Math.floor(Date.now() / 1000).toString(),
        'svix-signature': 'test_signature',
      },
      body: JSON.stringify(event),
    })

    const text = await response.text()
    console.log('Status:', response.status)
    console.log('Response:', text)
    
    if (response.ok) {
      console.log('✓ Webhook processed successfully')
    } else {
      console.log('✗ Webhook failed')
    }
  } catch (error) {
    console.error('✗ Error calling webhook:', error)
  }
}

async function runTests() {
  console.log('Starting webhook tests...')
  console.log('Make sure your Next.js dev server is running on port 3000')
  console.log('Note: Signature verification will fail - this is expected for local testing')
  
  // Test user creation
  await testWebhook(sampleUserCreated)
  
  // Wait a bit between requests
  await new Promise(resolve => setTimeout(resolve, 1000))
  
  // Test user update
  await testWebhook(sampleUserUpdated)
  
  // Wait a bit between requests
  await new Promise(resolve => setTimeout(resolve, 1000))
  
  // Test user deletion
  await testWebhook(sampleUserDeleted)
  
  console.log('\n=== Tests completed ===')
  console.log('\nTo test with real Clerk webhooks:')
  console.log('1. Configure Clerk webhook in dashboard')
  console.log('2. Use ngrok to expose your local server')
  console.log('3. Set CLERK_WEBHOOK_SECRET in .env.local')
}

runTests()
